server:
  port: 8082
spring:
  application:
    name: dm-user-consumer
eureka:
  instance:
    perfer-ip-address: true
  client:
    register-with-eureka: true
    fetch-regitry: true

    service-url:
      defaultZone: http://admin:admin123@localhost:7776/eureka/

# 开启服务降级
feign:
  hystrix:
    enabled: true