server:
  port: 8002
spring:
  application:
    name: dm-turbine-server
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:7776/eureka/
  instance:
    prefer-ip-address: true
turbine:
  cluster-name-expression: "'default'"
  combine-host-port: true
  app-config: dm-user-consumer,dm-user-consumer-second