server:
  port: 7900

spring:
  application:
    name: dm-config-server


#  # 使用文件系统存储配置系统
#  profiles:
#    active: native

  cloud:
    config:
      server:
        git:
          uri: https://github.com/wenpeng233/dm.git
          username: 907177955@qq.com
          password: wenp1893
          search-paths: config-repo
#        # 项目配置文件本地存放的位置
#        native:
#          searchLocations: classpath:/config-repo/{application}

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:7776/eureka/
