server:
  port: 10004
spring:
  application:
    name: dm-user-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.137.138:3306/redis-lock-test?useUnicode=true&zeroDateTimeBehavior=CONVERT_TO_NULL&characterEncoding=utf8&useSSL=false
    username: root
    password: changeme@123

eureka:
  instance:
    perfer-ip-address: true
  client:
    register-with-eureka: true
    fetch-regitry: true

    service-url:
      defaultZone: http://admin:admin123@localhost:7776/eureka/

  redis:
    redisson:
      config: classpath:redisson.yml
