spring:
  application:
    name: dm-gateway-zuul

server:
  port: 7600

zuul:
  #  # 添加默认的前缀，在转发到具体的微服务实例时会剥离该前缀
  #  prefix: /api
  #  # 在转发到具体的微服务实例时不要剥离prefix: /api这个前缀，支队prefix属性中的前缀起作用
  #  stripPrefix: false
  routes:
    # 将uri中的 dm-user-service 映射为user，zuul中的默认映射规则为: https://zuul的服务器地址:端口/eureka中注册的serviceId/服务对应的endpoint路径
    # 等价于 https://对应服务的服务器地址:端口/服务对应的endpoint路径
    dm-user-service: /user/**
#    # 对具体服务过滤请求头中的敏感信息，例如不想转发给第三方接口时，
#    dm-order-service:
#      customSensitiveHeaders: true
#      sensitiveHeaders: 这里设置要过滤的敏感的请求头信息
#  全局设置，对所有的服务过滤请求头中的敏感信息
#  sensitiveHeaders: 这里设置要过滤的敏感的请求头信息
#  下次转发不带忽略的请求头信息
#  ignoredHeaders: 这里设置要忽略的请求头信息

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:7776/eureka/


# 设置zuul请求的超时时间，默认1s，将default缓存特定的服务名称就是对特定的服务设置特定的超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000