server:
  port: 10003
spring:
  application:
    name: dm-seat-schedule-service
  datasource:
    # mysql 6及以上可以用以下的驱动包，同时maven中jdbc的依赖版本也要对应    #  通过useSSL=false参数避免出现jdbc连接数据库时报的协议错误
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.137.138:3306/redis-lock-test?useUnicode=true&zeroDateTimeBehavior=CONVERT_TO_NULL&characterEncoding=utf8&useSSL=false
    username: root
    password: changeme@123
  redis:
    host: redis://192.168.137.138:6379
    password:


## 开启服务降级
#feign:
#  hystrix:
#    enabled: true
#  httpclient:
#    enabled: false
#  okhttp:
#    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000


eureka:
  instance:
    perfer-ip-address: true
  client:
    register-with-eureka: true
    fetch-regitry: true

    service-url:
      defaultZone: http://admin:admin123@localhost:7776/eureka/


