server:
  port: 10003
spring:
  application:
    name: dm-seat-schedule-service

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.137.138:3306/redis-lock-test
    username: root
    password: changeme@123

  redis:
    cluster:
      nodes: 192.168.137.138:6379
    password:


# 开启服务降级
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true

eureka:
  instance:
    perfer-ip-address: true
  client:
    register-with-eureka: true
    fetch-regitry: true

    service-url:
      defaultZone: http://admin:admin123@localhost:7776/eureka/


